name: bug_free_blog_frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  go_router: ^16.2.1
  get_it: ^8.2.0
  injectable: ^2.3.2
  dio: ^5.4.0
  retrofit: ^4.4.2
  json_annotation: ^4.8.1
  equatable: ^2.0.5
  dartz: ^0.10.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.7.1
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^10.0.4

flutter:
  uses-material-design: true
